#ASM_OBJ += $(XCUBE_LIB_DIR)/Drivers/CMSIS/Device/ST/STM32L4xx/Source/startup_stm32l475xx.o 
ASM_OBJ += 

C_OBJ += $(XCUBE_LIB_DIR)/Drivers/CMSIS/Device/ST/STM32L4xx/Source/system_stm32l4xx.o 

#		$(XCUBE_LIB_DIR)/Drivers/CMSIS/Device/ST/STM32L4xx/Source/syscalls.o 

CXX_OBJ += 

INCLUDE_PATHS += -I. \
		-I$(XCUBE_LIB_DIR)/Drivers/CMSIS/Device/ST/STM32L4xx/Source \
		-I$(XCUBE_LIB_DIR)/Drivers/CMSIS/Device/ST/STM32L4xx/Include \
		-I$(XCUBE_LIB_DIR)/Drivers/CMSIS/Include 

