ASM_OBJ += 

C_OBJ += \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_comp.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_cortex.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_crc.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_crc_ex.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dma.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash_ex.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_gpio.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_hcd.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c_ex.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_iwdg.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_lptim.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_nand.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_nor.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pcd.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pcd_ex.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr_ex.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc_ex.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rng.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rtc.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rtc_ex.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_sai.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_smbus.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_spi.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_spi_ex.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_sram.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_swpmi.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim_ex.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tsc.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_uart.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_uart_ex.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_usart.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_wwdg.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_comp.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_crc.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_crs.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_exti.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_fmc.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_gpio.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_i2c.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_lptim.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_lpuart.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_pwr.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_rcc.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_rng.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_rtc.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_spi.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_swpmi.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_tim.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_usart.o \
		${XCUBE_LIB_DIR}/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_utils.o \

CXX_OBJ += 

INCLUDE_PATHS += -I. \
		-I$(XCUBE_LIB_DIR)/Drivers/STM32L4xx_HAL_Driver/Inc 

